---
- name: install packages
  yum:
    name:
      - gcc
      - git
    state: latest

- name: Get golang tarball
  get_url:
    url: "https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz"
    dest: /tmp/
  register: new_archive

- name: Unarchive golang
  unarchive:
    src: /tmp/go1.12.7.linux-amd64.tar.gz
    dest: /usr/local/
    copy: no
  when: new_archive|changed

- name: Add Go to the path
  lineinfile:
    path: /etc/profile.d/path.sh
    state: present
    create: yes
    line: "{{ item }}"
    mode: 0755
  with_items:
    - 'export PATH=$PATH:/usr/local/go/bin'
    - 'export GOBIN=$HOME/projects/bin'
    - 'export GOPATH=$HOME/projects'
    - 'export PATH=$PATH:~/projects/bin'

- name: Create Go environment
  file:
    path: /root/projects/{{item}}
    state: directory
    recurse: yes
  with_items:
    - bin
    - src
    - pkg

- name: Get CFSSL
  command: go get -u github.com/cloudflare/cfssl/cmd/...
  args:
    creates: /root/projects/bin/cfssl
