# COMMON
- name: setup CA
  import_tasks: common.yml

# ROOT CA
- name: setup root CA
  import_tasks: rootca.yml
  when: "'rootca' in group_names"

# INTERMEDIATE CA
- name: setup intermediate CA
  import_tasks: intermediateca.yml
  when: "'intermediateca' in group_names"

# CERTIFICATES
- name: generate client certificates
  import_tasks: certs.yml
  when: "'intermediateca' in group_names"